version: '2.1'

networks:
  branchtalk-monolith:
    driver: bridge

services:
  postgres:
    image: 'bitnami/postgresql:12-debian-10'
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'postgres_data:/bitnami/postgresql'
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 4
    networks:
      - branchtalk-monolith

  zookeeper:
    image: 'bitnami/zookeeper:3-debian-10'
    restart: always
    ports:
      - '127.0.0.1:2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - branchtalk-monolith

  kafka:
    image: 'bitnami/kafka:2-debian-10'
    restart: always
    ports:
      - '127.0.0.1:9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INTERNAL://kafka:9094,OUTSIDE://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9094,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 4
    networks:
      - branchtalk-monolith

  redis:
    image: 'bitnami/redis:5.0-debian-10'
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redis_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - branchtalk-monolith

volumes:
  postgres_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  redis_data:
    driver: local
